# Generated by Django 4.1.1 on 2022-09-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semi_RestfulTVShows', '0002_alter_tvshow_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='desc',
            field=models.CharField(default='This TV Show has no description', max_length=255),
            preserve_default=False,
        ),
    ]
