# Generated by Django 4.1.1 on 2022-09-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Semi_RestfulTVShows', '0003_tvshow_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='netwoork',
            new_name='network',
        ),
    ]
